# Generated by Django 4.0.6 on 2023-09-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
