# Generated by Django 4.0.6 on 2023-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_alter_admin_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=9800000000, max_length=10),
        ),
    ]
