# Generated by Django 4.0.6 on 2023-10-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(default=9800000000, max_length=10),
        ),
    ]
