# Generated by Django 4.0.6 on 2023-10-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_alter_order_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
